# Generated by Django 4.2.14 on 2025-01-01 14:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
        ('ward', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ward',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='wards', to='user.myuser', to_field='ward'),
        ),
    ]
