# Generated by Django 4.2.14 on 2025-01-01 15:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ward', '0002_alter_ward_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ward',
            old_name='user',
            new_name='name',
        ),
    ]
