# Generated by Django 4.2.14 on 2025-01-01 15:21

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('content', '0001_initial'),
        ('ward', '0003_rename_user_ward_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ward',
            name='category',
            field=models.ForeignKey(limit_choices_to={'name__in': ['Events & Notice']}, null=True, on_delete=django.db.models.deletion.CASCADE, to='content.category'),
        ),
        migrations.AlterField(
            model_name='ward',
            name='name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='wards', to=settings.AUTH_USER_MODEL),
        ),
    ]
