# Generated by Django 4.2.14 on 2025-03-16 15:35

import autoslug.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ward', '0004_alter_ward_category_alter_ward_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ward',
            name='slug',
            field=autoslug.fields.AutoSlugField(blank=True, editable=False, null=True, populate_from='title', unique=True),
        ),
        migrations.AlterField(
            model_name='ward',
            name='title',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
