# Generated by Django 4.2.14 on 2025-03-16 15:39

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('ward', '0005_alter_ward_slug_alter_ward_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ward',
            name='name',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='wards', to=settings.AUTH_USER_MODEL),
        ),
    ]
