# Generated by Django 4.2.14 on 2025-03-17 05:33

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('ward', '0006_alter_ward_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ward',
            name='name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='wards', to=settings.AUTH_USER_MODEL),
        ),
    ]
